USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ZOMATO_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

--DATABASE AND MEDALLION SCHEMA
CREATE DATABASE IF NOT EXISTS ZOMATO;
CREATE SCHEMA IF NOT EXISTS ZOMATO.BRONZE;   --Iceberg tables Spark wrote (bdt sources)
CREATE SCHEMA IF NOT EXISTS ZOMATO.RAW;      -- only used by the COPY fallback path
CREATE SCHEMA IF NOT EXISTS ZOMATO.STAGING;  -- cleaned/conformed (dbt) Silver
CREATE SCHEMA IF NOT EXISTS ZOMATO.MARTS;     --Gold layer 
CREATE SCHEMA IF NOT EXISTS ZOMATO.SNAPSHOTS;  --SCD2 history (dbt)
CREATE SCHEMA IF NOT EXISTS ZOMATO.AI;


-- a role dbt/airflow will use
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT ALL ON DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE ZOMATO TO ROLE DBT_ROLE;

SET my_user = current_user();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($my_user);

SELECT 'setup complete' AS status;
