-- Instead of CREATE OR REPLACE every time, do this once:
CREATE STORAGE INTEGRATION IF NOT EXISTS ZOMATO_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::174689656946:role/snowflake-s3-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://zomato-ai-etl/');

GRANT USAGE ON INTEGRATION ZOMATO_S3_INT TO ROLE DBT_ROLE;
DESC INTEGRATION ZOMATO_S3_INT;