USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO;
USE SCHEMA RAW;


CREATE OR REPLACE FILE FORMAT ZOMATO.RAW.CSV_FMT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    TRIM_SPACE = FALSE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', '\\N', 'NULL')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STAGE ZOMATO.RAW.ZOMATO_RAW_STAGE
    STORAGE_INTEGRATION = ZOMATO_S3_INT
    URL = 's3://zomato-ai-etl/raw/'
    FILE_FORMAT = ZOMATO.RAW.CSV_FMT;

LIST @ZOMATO.RAW.ZOMATO_RAW_STAGE;
    